### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by DrCryptoN3rd** [nervosnetwork/neuron#2403]
Hello there

I have a newly installed wallet on Ubuntu, it keeps connecting but never connects or starts syncing. 
Tried to restart and clear Cache, did't work.
Any ideas?

[neuron_debug_1653904335457.zip](https://github.com/nervosnetwork/neuron/files/8797363/neuron_debug_1653904335457.zip)

![Bildschirmfoto von 2022-05-30 11-54-31](https://user-images.githubusercontent.com/84883231/170967656-531fa1fe-41e2-459e-bde4-adfd2a873fbc.png)

**Comment by Keith-CY** [comment]
Hi @DrCryptoN3rd 

From the ckb-bundled.log
```
2022-05-30 07:23:32.352 +02:00 main ERROR panic  thread 'main' panicked at 'Internal(DataCorrupted(failed to open database: IO error: While lock file: /home/user/.config/Neuron/chains/mainnet/data/db/LOCK: Resource temporarily unavailable))': db/src/db.rs:99   0: ckb_logger_service::setup_panic_logger::{{closure}}
```

There's a lock file stopping running ckb node inside neuron, removing `/home/user/.config/Neuron/chains/mainnet/data/db/LOCK` should fix it.

**Comment by DrCryptoN3rd** [comment]
[neuron_debug_1653924563124.zip](https://github.com/nervosnetwork/neuron/files/8799456/neuron_debug_1653924563124.zip)
Did that now it's not even trying to connect.

**Comment by Keith-CY** [comment]
> [neuron_debug_1653924563124.zip](https://github.com/nervosnetwork/neuron/files/8799456/neuron_debug_1653924563124.zip) Did that now it's not even trying to connect.

Hi @DrCryptoN3rd 

The `bundled-ckb.log` shows ckb node is running and `main.log` shows neuron is trying to boost ckb-indexer `[2022-05-30 17:22:10.805] [info] Indexer:	start: PORT: 8118`, which is the synchronization module of neuron, but it hangs(3 times). This happens when ckb-indexer was not closed properly last time.

Please check if ckb-indexer is running (with command line in terminal `lsof -i:8118`) when neuron is off. If yes, you may have to kill ckb-indexer process manually and relaunch neuron. 

If neuron still hangs with log `[info] Indexer:	start: PORT: 8118...`, it should be an error related to `ckb-indexer` and I'll ask the developer for help.

**Comment by DrCryptoN3rd** [comment]
I did kill all the ckb processes, restarted and it still hangs with log [info] Indexer: start: PORT: 8118...
[neuron_debug_1653936897082.zip](https://github.com/nervosnetwork/neuron/files/8800281/neuron_debug_1653936897082.zip)
